# Generated by Django 3.2.6 on 2021-08-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20210822_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_area', to='provider.provider'),
        ),
    ]
